openapi: 3.0.0
Authorization: Bearer <token>
info:
  title: Mock API
servers:
  - url: https://training-1.chondi.net/api
  - url: http://127.0.0.1:8000/api
paths:
  /auth/login:
    $ref: auth/Login.yaml
  /auth/facebook/login:
    $ref: auth/FetchUrlSocial.yaml
  /auth/facebook/callback:
    $ref: auth/LoginSocial.yaml
  /auth/register:
    $ref: users/Register.yaml
  /users/change-password:
    $ref: users/ChangePassword.yaml
  /users/create-vote:
    $ref: users/CreateVote.yaml
  /users/up-vote:
    $ref: users/UpVote.yaml
  /votes:
    $ref: vote/ListVotes.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
