openapi: 3.0.0
Authorization: Bearer <token>
info:
  title: Mock API
servers:
  - url: https://training-1.chondi.net/api
  - url: http://127.0.0.1:8000/api
paths:
  /auth/login:
    $ref: auth/Login.yaml
  /auth/facebook/login:
    $ref: auth/FetchUrlSocial.yaml
  /auth/facebook/callback:
    $ref: auth/LoginSocial.yaml
  /auth/register:
    $ref: users/Register.yaml
  /users/change-password:
    $ref: users/ChangePassword.yaml
  /users/create-vote:
    $ref: users/CreateVote.yaml
  /users/up-vote:
    $ref: users/UpVote.yaml
  /users/offer-vote:
    $ref: users/OfferVote.yaml
  /users/delete-vote/{id}:
    $ref: users/DeleteVote.yaml
  /users/list-votes:
    $ref: users/YourListVotes.yaml
  /users/{id}/list-votes:
    $ref: users/OtherListVotes.yaml
  /users/cancel-up-vote:
    $ref: users/UnUpVote.yaml
  /votes/:
    $ref: votes/ListVotes.yaml
  /votes/{id}:
    $ref: votes/Show.yaml
  /votes/{id}/update-title:
    $ref: votes/UpdateVoteTitle.yaml
  /votes/{id}/add-options:
    $ref: votes/AddOptions.yaml
  /options/{id}:
    put:
      $ref: options/UpdateOption.yaml
    delete:
      $ref: options/DeleteOption.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
